---
- name: Create working directory
  shell: mkdir {{ REPORT_DIR }}
  ignore_errors: yes
  
- name: Retrieve tenantIDs
  shell: keystone --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }}
         tenant-list | awk 'NR > 3 { print $2 }'
  register: tenantid

- name: Add report header
  shell: ( echo "+------------------------------------+"; echo "| Tenant Usage Report                |"; echo "| Created at {{ lookup('pipe', 'date +%Y-%m-%d%t%X') }}  |"; echo "+------------------------------------+"; echo " "; ) >> {{ REPORT_DIR }}/os_usage_report_{{ lookup('pipe', 'date +%Y%m%d') }}.log 

- name: Record tenant usage
  shell: ( echo "Tenant - {{ item }}" && nova --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }}
         usage --start {{ RPTSTART }} --end {{ RPTEND }} --tenant {{ item }} && echo " " ) >> {{ REPORT_DIR }}/os_usage_report_{{ lookup('pipe', 'date +%Y%m%d') }}.log
  with_items: tenantid.stdout_lines

- name: Retrieve tenant usage report file
  fetch: src={{ REPORT_DIR }}/os_usage_report_{{ lookup('pipe', 'date +%Y%m%d') }}.log dest={{ REPORT_DEST }} flat=yes