---
- name: Create working directory
  shell: mkdir {{ REPORT_DIR }}
  ignore_errors: yes

- name: Copy the tenant_report script
  copy: src=tenant_report.sql dest=/usr/share mode=0755
  
- name: Add report header
  shell: ( echo "+-------------------------+"; echo "| Cloud Tenant Report     |"; echo "+-------------------------+"; ) >> {{ REPORT_DIR }}/os_report_{{ lookup('pipe', 'date +%Y%m%d') }}.log 

- name: Execute tenant report
  shell: chdir=/usr/bin mysql -u root --password={{ MYSQLPASS }} --table < /usr/share/tenant_report.sql >> {{ REPORT_DIR }}/os_report_{{ lookup('pipe', 'date +%Y%m%d') }}.log