---
- name: Combine Infrastructure and Core OS output
  shell: cat {{ REPORT_DEST }}/core_os_check_{{ lookup('pipe', 'date +%Y%m%d') }}.txt >> {{ REPORT_DIR }}/os_health_check_{{ lookup('pipe', 'date +%Y%m%d') }}.txt

- name: Check OS service status
  shell: ansible -i {{ DEPLOY_LOC }}/inventory/dynamic_inventory.py  {{ item.0.name }} -m shell 
         -a "service {{ item.1 }} status" >> {{ REPORT_DIR }}/os_health_check_{{ lookup('pipe', 'date +%Y%m%d') }}.txt
  with_subelements:
    - os_group
    - process